### ISSUE TITLE
Square Layout

### ISSUE THREAD

**Issue by anticafe** [devsoulwolf/Android-RatioLayout#2]
I know it's easy to create square layout - it's special case of RatioLayout with `widthRatio=1` and `heightRatio=1`. However, could you please make square layout built-in in this library?

**Comment by devsoulwolf** [comment]
@anticafe I'm very sorry, I don't quite understand what you mean, or don't know what do you mean that Square Layout!

**Comment by anticafe** [comment]
@devsoulwolf Square Layout is layout with width and height equal.

**Comment by ja5h** [comment]
Though the idea of square layout is good, it is a very specific case with limited applications. So, it is better to use the normal layout with width : height = 1 : 1.
